### ISSUE TITLE
Mean of empty slice error whilst running CHAZ.py (dPIwspd and bt1.StormLon)

### ISSUE THREAD

**Issue by alexandrefierro** [cl3225/CHAZ#5]
I am running the model for the 2000,2001,2002 example provided (as the PI.mat files are available).

After running the pre-processing step successfully, I am encountering the following issues when running the CHAZ model (below) related to dPIwspd variables (what are they?) and arg_last in src/caldetsto_track_lysis.py, line 304-305 being out of bounds: 
                 elif var in 'dPIwspd':
                   rvar = nanmean(bt.PIwspdMean[it:it+lT+1,index])-v0
                elif var in 'dPIwspd2':
                   rvar = (nanmean(bt.PIwspdMean[it:it+lT+1,index])-v0)**2
                 elif var in 'dPIwspd3':
                    rvar = (nanmean(bt.PIwspdMean[it:it+lT+1,index])-v0)**3

Any idea how to fix this? Thank you.

ERA5 CHAZ_2000_2002 TCGI_CRH_PI
get Seeding ratio for ERA5 CHAZ_2000_2002
The seeding ratio is 1.52601443864
2000 TCGI
2000 Bam
[########################################] | 100% Completed | 11min 49.4s
removeland
give times
2000 calculate predictors
[########################################] | 100% Completed | 57.7s
done translation speed 57.7507209778
[                                        ] | 0% Completed |  0.7s /conda/x86_64/envs/py27/lib/python2.7/site-packages/numpy/ma/core.py:5160: RuntimeWarning: Mean of empty slice.
  dtype=dtype, **kwargs)[()]
/conda/x86_64/envs/py27/lib/python2.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
[########################################] | 100% Completed | 36.3s
 done calPredictors 36.317909956
2000 calculate Intensitys
[                                        ] | 0% Completed |  0.0s /CHAZ/CHAZvBeta/tools/regression4.py:1206: RuntimeWarning: Mean of empty slice
[########################################] | 100% Completed |  0.5s
[########################################] | 100% Completed |  1.5s
[########################################] | 100% Completed |  1.4s
[########################################] | 100% Completed |  1.5s
[########################################] | 100% Completed |  1.5s
[########################################] | 100% Completed |  1.4s
[########################################] | 100% Completed |  1.5s
[########################################] | 100% Completed |  1.4s
[########################################] | 100% Completed |  1.5s
[########################################] | 100% Completed |  1.5s
[########################################] | 100% Completed |  1.5s
Traceback (most recent call last):
  File "CHAZ.py", line 64, in <module>
    CHAZ_detsto.calIntensity(EXP,iy,ichaz)
  File "/lustre01/vol0/1163ow/tc_risk/CHAZ/CHAZvBeta/src/caldetsto_track_lysis.py", line 304, in calIntensity
    for nn in range(bt1.StormLon.shape[1])] for iN in range(40)])
IndexError: index 10 is out of bounds for axis 2 with size 10

When commenting out the section of the code causing the error below - which as I gather removes spurious tracks - the model seems to run & I was able to plot the track data (for year 2000):

"src/caldetsto_track_lysis.py:

304         #arg_last = np.array([[pd.Series(bt1.stochastic[:,nn,iN]).last_valid_index()\
305         #            for nn in range(bt1.StormLon.shape[1])] for iN in range(40)])
306         #arg_last[arg_last == np.array(None)] = 0
307         #arg_last = arg_last.astype(None)
308         #arg_last = np.int_(arg_last).T
309         #basin2 = np.array([util.defineBasin(bt1.StormLon[arg_last[nn],nn],\
310         #           bt1.StormLat[arg_last[nn],nn],xbin,ybin,basinMap) \
311         #           for nn in range(arg_last.shape[0])])
312         #iS1, iN1 = np.where((((basin0<5)&(basin2>=5))|((basin0>=5)&(basin2<5))|\
313         #            ((basin0==0)&(basin2==1))))
314         #bt1.stochastic[:,iS1,iN1] = np.float('nan')
315         #iS1,iN1 = np.where((((basin0<5)&(basin1>=5))|((basin0>=5)&(basin1<5))|\
316         #            ((basin0==0)&(basin1==1))))
317         #bt1.stochastic[:,iS1,iN1] = np.float('nan')

**Comment by alexandrefierro** [comment]
Update: After changing the dimension 3 of the array bt1.stochastic[:,nn,iN]) and np.tile(basin,(10,1)).T from 40 to 10 in src/caldetsto_track_lysis.py:

302         basin0 = np.tile(basin,(10,1)).T
303 

305         arg_last = np.array([[pd.Series(bt1.stochastic[:,nn,iN]).last_valid_index()\
306                     for nn in range(bt1.StormLon.shape[1])] for iN in range(10)])
307         arg_last[arg_last == np.array(None)] = 0

The code ran to completion for 2000-2002. Still, the "Mean of empty slice" issues regarding the dPIwspd variables remain.
